// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0pSGqtk7FhOjIzQRC6kYnV4vokKMAHc',
    appId: '1:666672497487:web:a20ebe4a7ddffea3ad3b3a',
    messagingSenderId: '666672497487',
    projectId: 'proyecto-final-dam-d673f',
    authDomain: 'proyecto-final-dam-d673f.firebaseapp.com',
    storageBucket: 'proyecto-final-dam-d673f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-pD_9JzUhy692GIbW3eJlJDnsi95gf7M',
    appId: '1:666672497487:android:da00e14873ff05c5ad3b3a',
    messagingSenderId: '666672497487',
    projectId: 'proyecto-final-dam-d673f',
    storageBucket: 'proyecto-final-dam-d673f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvJqkwOGUSGxA7i90VtVtC59xYN_rdIF4',
    appId: '1:666672497487:ios:88619e68b1d91972ad3b3a',
    messagingSenderId: '666672497487',
    projectId: 'proyecto-final-dam-d673f',
    storageBucket: 'proyecto-final-dam-d673f.appspot.com',
    iosBundleId: 'com.example.damProyectoFinal',
  );
}
